/** 每日一问题库:按 UTC 日期轮换,两人每天看到同一道题 */

export const QUESTIONS = [
  '今天最让你开心的一件小事是什么?',
  '如果现在能瞬间移动到对方身边,你最想一起做什么?',
  '最近一次因为想起对方而笑出来,是什么时候?',
  '你最喜欢对方身上的哪个小习惯?',
  '下次见面,最想一起吃的第一顿饭是什么?',
  '如果我们一起养宠物,你想养什么?给它起什么名字?',
  '你还记得我们第一次聊天聊了什么吗?',
  '最近有什么压力或烦恼,想说给对方听?',
  '如果周末突然多出一天假期,你想怎么过?',
  '对方做过的哪件事,让你觉得特别被爱?',
  '你心目中我们五年后的生活是什么样子?',
  '最近循环播放的一首歌是什么?为什么喜欢?',
  '如果只能推荐一部电影给对方,你选哪部?',
  '小时候的你,是什么样子的小孩?',
  '你最想和对方一起去的三个地方是哪里?',
  '今天的天气怎么样?描述一下你窗外的样子。',
  '最近吃到最好吃的东西是什么?',
  '如果可以学会一项新技能,你想学什么?',
  '你觉得我们最有默契的瞬间是什么时候?',
  '有什么话想对一年前的自己说?',
  '对方哪个表情或动作最可爱?',
  '你最近读到/看到最有意思的东西是什么?',
  '如果我们开一家小店,你想开什么店?',
  '今天有没有哪个瞬间特别想对方?',
  '你的理想周末早晨是什么样的?',
  '最近一次大笑是因为什么?',
  '你希望我们一起养成什么小习惯?',
  '如果能回到过去重温我们的某一天,你选哪天?',
  '最近你为什么事情感到骄傲?',
  '你觉得对方最近辛苦吗?想对TA说什么?',
  '如果中了一百万,你第一件事做什么?',
  '你最怀念家乡的什么味道?',
  '形容一下今天的心情,用一种食物。',
  '我们的下一个小目标,你觉得应该是什么?',
  '你最近学到的一个新知识是什么?',
  '如果给我们的故事写一本书,书名叫什么?',
  '你今天穿了什么?拍张照发给对方吧!',
  '最想让对方为你做的一道菜是什么?',
  '你觉得异地最难的部分是什么?我们怎么让它好受一点?',
  '今天最感激的一件事是什么?',
  '如果我们有一首"我们的歌",你觉得是哪首?',
  '你想给我们未来的家添置的第一件东西是什么?',
  '最近有什么想买但犹豫的东西?',
  '你眼中我们最大的不同点和最大的共同点是什么?',
  '如果明天可以见面一小时,你想怎么安排?',
  '你最喜欢自己身上的哪一点?',
  '最近有没有梦到过对方?梦到了什么?',
  '冬天和夏天,你更喜欢和对方一起过哪个?为什么?',
  '你觉得最浪漫的小事是什么?',
  '现在你的桌面/房间是什么样子?描述一下。',
  '如果我们交换一天生活,你最想体验我哪部分日常?',
  '你希望对方多夸你哪一点?',
  '最近让你觉得"长大了"的一个瞬间?',
  '我们之间你最想保留一辈子的小传统是什么?',
  '如果今天可以不上班/不上课,你会拿来做什么?',
  '你想对此刻正在看这个问题的TA说一句什么?',
  '下一次纪念日,你想怎么庆祝?',
  '你手机相册最近一张照片是什么?讲讲它的故事。',
  '如果用三个词形容现在的我们,你会用哪三个?',
  '今晚睡前,你最想听到对方说的一句话是什么?',
] as const

/** 英文题库(与中文一一对应;日语界面暂用英文题) */
const QUESTIONS_EN = [
  'What little thing made you happiest today?',
  'If you could teleport to each other right now, what would you do together first?',
  'When did you last laugh just from thinking of each other?',
  "What's your favorite little habit of theirs?",
  'Next time we meet, what should our first meal be?',
  'If we got a pet together, what would it be and what would you name it?',
  'Do you remember what our very first chat was about?',
  "Any stress or worries lately you'd like to share?",
  'If a surprise extra day off appeared this weekend, how would you spend it?',
  'What did they do that made you feel especially loved?',
  'What does our life look like five years from now, in your mind?',
  "What song is on repeat for you lately, and why?",
  'If you could recommend only one movie to each other, which one?',
  'What were you like as a kid?',
  'Top three places you want to visit together?',
  "How's the weather there? Describe the view outside your window.",
  "What's the tastiest thing you've eaten recently?",
  'If you could master one new skill, what would it be?',
  'When do you feel we are most in sync?',
  'What would you say to yourself from one year ago?',
  'Which of their expressions or gestures is the cutest?',
  "What's the most interesting thing you've read or seen lately?",
  'If we opened a little shop together, what would we sell?',
  'Was there a moment today you really missed them?',
  "What's your ideal weekend morning like?",
  'What made you laugh out loud most recently?',
  'What little habit should we build together?',
  'If you could relive one of our days, which one?',
  'What are you proud of lately?',
  'Do you think they have been working hard? Anything to tell them?',
  'If you won a million, what would you do first?',
  'Which taste of home do you miss the most?',
  "Describe today's mood as a food.",
  'What should our next little goal be?',
  "What's one new thing you learned recently?",
  'If our story became a book, what would its title be?',
  'What are you wearing today? Send a pic!',
  'What dish do you most want them to cook for you?',
  "What's the hardest part of long distance, and how can we soften it?",
  'What are you most grateful for today?',
  'If we had "our song", which one would it be?',
  'What is the first thing you want to buy for our future home?',
  "Anything you've been hesitating to buy lately?",
  'Our biggest difference and biggest similarity?',
  'If we could meet for just one hour tomorrow, how would you plan it?',
  'What do you like most about yourself?',
  'Have you dreamed of them lately? What happened?',
  'Winter or summer together — which do you prefer, and why?',
  "What's the most romantic small gesture to you?",
  'What does your desk/room look like right now? Describe it.',
  'If we swapped lives for a day, what part of mine would you try first?',
  'What would you like to be complimented on more?',
  'A recent moment that made you feel grown-up?',
  'Which little tradition of ours should we keep forever?',
  'If you were free from work/school today, what would you do?',
  'Say one thing to the person reading this question right now.',
  'How should we celebrate our next anniversary?',
  'What is the latest photo in your camera roll? Tell its story.',
  'Describe us right now in three words.',
  'What would you most like to hear from them before sleep tonight?',
] as const

/** 日文题库(与中文一一对应) */
const QUESTIONS_JA = [
  '今日いちばん嬉しかった小さなことは?',
  '今すぐ相手の隣に瞬間移動できたら、まず何を一緒にしたい?',
  '最近、相手を思い出して笑ったのはいつ?',
  '相手のいちばん好きな小さなクセは?',
  '次に会えたら、最初に一緒に食べたいものは?',
  'もし一緒にペットを飼うなら何にする?名前は?',
  '私たちの最初の会話、覚えてる?',
  '最近のストレスや悩み、聞かせて?',
  '週末に突然休みが1日増えたら、どう過ごす?',
  '相手のどんな行動に、特に愛を感じた?',
  '5年後の私たちの暮らし、どんなイメージ?',
  '最近リピートしている曲は?その理由は?',
  '相手に1本だけ映画を勧めるなら、どれ?',
  '子どもの頃のあなたはどんな子だった?',
  '一緒に行きたい場所トップ3は?',
  'そっちの天気はどう?窓の外の景色を教えて。',
  '最近食べたいちばん美味しいものは?',
  '新しいスキルを1つ習得できるなら何にする?',
  '私たちが最も息ぴったりな瞬間はいつだと思う?',
  '1年前の自分に何て言いたい?',
  '相手のどの表情や仕草がいちばん可愛い?',
  '最近読んだ・見た中でいちばん面白かったものは?',
   'もし二人で小さなお店を開くなら、何のお店?',
  '今日、相手をすごく恋しく思った瞬間はあった?',
  '理想の週末の朝はどんな感じ?',
  '最近、声を出して笑ったのはどんなこと?',
  '二人で一緒に作りたい小さな習慣は?',
  '私たちのある一日をもう一度過ごせるなら、いつの日?',
  '最近、自分を誇らしく思ったことは?',
  '相手は最近頑張ってると思う?伝えたいことは?',
  'もし100万当たったら、最初に何をする?',
  'いちばん恋しい故郷の味は?',
  '今日の気分を食べ物で例えると?',
  '私たちの次の小さな目標は何にする?',
  '最近学んだ新しい知識は?',
  '私たちの物語を本にするなら、タイトルは?',
  '今日は何を着てる?写真を送って!',
  '相手に作ってほしい料理は?',
  '遠距離でいちばん辛いことは?どうすれば楽になる?',
  '今日いちばん感謝していることは?',
  '「私たちの歌」があるとしたら、どの曲?',
  '未来の家に最初に置きたいものは?',
  '最近、買おうか迷っているものは?',
  '私たちの最大の違いと最大の共通点は?',
  '明日1時間だけ会えるなら、どう過ごす?',
  '自分のいちばん好きなところは?',
  '最近、相手の夢を見た?どんな夢?',
  '冬と夏、どっちを一緒に過ごしたい?理由は?',
  'あなたにとって最高にロマンチックな小さなことは?',
  '今の机/部屋はどんな様子?教えて。',
  '1日だけ生活を交換できたら、相手のどの日常を体験したい?',
  'もっと褒めてほしいところは?',
  '最近「大人になったな」と感じた瞬間は?',
  'ずっと残したい私たちの小さな伝統は?',
  '今日仕事も学校もなかったら、何をする?',
  '今この質問を読んでいる相手に、一言どうぞ。',
  '次の記念日はどう祝いたい?',
  'カメラロールの最新の写真は?その物語を教えて。',
  '今の私たちを三つの言葉で表すと?',
  '今夜眠る前に、相手から言ってほしい一言は?',
] as const

import { getLang } from './i18n'

/** 按 UTC 日期取当天的问题(顺序轮换;两人各看各的语言,题序一致) */
export function questionForDate(utcDate: string): string {
  const days = Math.floor(Date.parse(`${utcDate}T00:00:00Z`) / 86_400_000)
  const idx = days % QUESTIONS.length
  const lang = getLang()
  return lang === 'zh' ? QUESTIONS[idx] : lang === 'ja' ? QUESTIONS_JA[idx] : QUESTIONS_EN[idx]
}
